name: Test with system Python

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  test-system:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        architecture: [x64]
        python-version: ['3.x']
        julia-version:
          - '1'
          - 'nightly'
        include:
          - os: macos-latest
            architecture: arm64
            python-version: '3.x'
            julia-version: '1'
          - os: macos-latest
            architecture: arm64
            python-version: '3.x'
            julia-version: 'nightly'
          - os: macos-latest
            architecture: x64 # agent is arm64 (runs under Rosetta)
            python-version: '3.x'
            julia-version: '1'
          - os: macos-latest
            architecture: x64 # agent is arm64 (runs under Rosetta)
            python-version: '3.x'
            julia-version: 'nightly'
          # 32 bit Windows:
          - os: windows-latest
            architecture: x86
            python-version: '3.x'
            julia-version: '1'
          # Sweep python-version and julia-version only on Ubuntu:
          - os: ubuntu-latest
            architecture: x64
            python-version: '3.10'
            julia-version: '1'
          - os: ubuntu-latest
            architecture: x64
            python-version: '3.x'
            julia-version: '1.5'
          - os: ubuntu-latest
            architecture: x64
            python-version: '3.x'
            julia-version: '1.4'
      fail-fast: false
    name: Test
      Julia ${{ matrix.julia-version }}
      Python ${{ matrix.python-version }}
      ${{ matrix.os }} ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install numpy
        run: python -m pip install --user numpy
        if: ${{ !(matrix.os == 'macos-latest' && matrix.architecture == 'x64') }}
      - name: Install numpy (Rosetta)
        run: arch -x86_64 python -m pip install --user numpy
        if: ${{ matrix.os == 'macos-latest' && matrix.architecture == 'x64' }}
      - name: Install virtualenv
        run: python -m pip install virtualenv
        if: ${{ !(matrix.os == 'macos-latest' && matrix.architecture == 'x64') }}
      - name: Install virtualenv (Rosetta)
        run: arch -x86_64 python -m pip install virtualenv
        if: ${{ matrix.os == 'macos-latest' && matrix.architecture == 'x64' }}
      - run: virtualenv --version
      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.architecture }}
          show-versioninfo: true
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: python
      - run: julia test/check_deps_version.jl ${{ matrix.python-version }}
      - uses: julia-actions/julia-runtest@v1
        env:
          # Windows temp directories break the CI:
          #  https://github.com/actions/runner-images/issues/712
          #  so, we use
          #  https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
          _TMP_DIR: ${{ runner.temp }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
