name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
  pull_request:
jobs:
  TagBot:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
